command: ['npm', 'run', 'start']
env:
  - name: PGHOST
    value: "ep-icy-voice-d1skfonp.database.us-west-2.cloud.databricks.com"
  - name: PGPORT
    value: "5432"
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGSSLMODE
    value: "require"
  - name: LAKEBASE_ENDPOINT
    value: "projects/casperskitchens-support-db/branches/production/endpoints/ep-icy-voice-d1skfonp"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "e5ed18828056f3cf"
  - name: SUPPORT_AGENT_ENDPOINT_NAME
    value: "caspers_support_agent"